### ISSUE TITLE
Error using hsimp.setPeriodDictionary(array)

### ISSUE THREAD

**Issue by Tinsus** [howsecureismypassword/hsimp#10]
Hi there,

first of all: a big thanks for including the language tools to the latest update.
Now I found a moment of time to include this new changes to my code.

I use hsimp.setPeriodDictionary(array) like the following:
`hsimp.setPeriodDictionary(getLocaArray())`
`function getLocaArray() {
return [
		{
			"singular": GetLoca("HSIMP_E_24_S"),
			"plural": GetLoca("HSIMP_E_24_P"),
			"seconds": 1e-24
		}
//+ all the other entries
]
}`
GetLoca just returns a localized string like "yoctosecond" as string based on the entered key.

Here is the error: this works fine for all but the seconds-entry. if the returned string is different from "second" and "seconds" the whole dictionary gets broken and everything I get is "instant" or "forever" as return of the check.

Do you have an idea for the origin of this error?

**Comment by smallhadroncollider** [comment]
I think the `second` property name is hardcoded as the default value into the bit of code that works out periods.

https://github.com/howsecureismypassword/modules-period/blob/develop/period.js#L9

Come September I'm hoping to rewrite the modules in ES6, so I'll be able to sort out issues like this then.

**Comment by smallhadroncollider** [comment]
One year later (almost). I have started rewriting it in PureScript, which will hopefully get rid of this issue. But going on paternity leave soon, so might be a while. Sorry!

**Comment by linuxlurak** [comment]
"second" still hardcoded it seems. Can change seconds to "Sekunden" (DE) without any issues. Are you interested in a german translation? Where to post?

**Comment by smallhadroncollider** [comment]
The [PureScript version](https://github.com/howsecureismypassword/modules-purescript) doesn't have this issue. I've not quite got round to writing up the docs properly for it, but once I do I'm going to make this repo as deprecated.

**Comment by smallhadroncollider** [comment]
To do a German translation you'd just need to update the [dictionary files](https://github.com/howsecureismypassword/modules-purescript/tree/develop/dictionaries) and pass them in.

**Comment by linuxlurak** [comment]
Thanks for your reply. I already did the translation. Are you interested to have this translation in your repository?

I'll post it here:
<details>
  <summary>German Translation (Click to expand)</summary>
/* Verschiedenes */
/* hsimp.setDictionary(); */
{
        "instantly": "sofort",
        "forever": "Ewigkeiten",
    }); 

/*Checker Definitionen*/
/* hsimp.setCheckerDictionary(); */
{
    "common": {
        "name": "Gewöhnliches Passwort: Das Passwort ist unter den top {{ value }} Passwörtern.",
        "message": "Das Passwort wird sehr häufig benutzt. Sie sollten es umgehend ändern."
    },
    "xkcd": {
        "name": "xkcd",
        "message": "I suspect the password crackers might be on to this one by now..."
    },
    "jeff": {
        "name": "There's always a back door...",
        "message": "\"The guy who made the software was called Jeff Jeffty Jeff. Born on the first of Jeff, nineteen-jeffty-jeff.\""
    },
    "lengthVeryShort": {
        "name": "Länge: Sehr kurz",
        "message": "Das Passwort ist sehr kurz. Je länger das Passwort, je sicherer ist es. Sie sollten es umgehend ändern."
    },
    "possiblyWord": {
        "name": "Möglicherweise ein Wort",
        "message": "Das Passwort könnte möglicherweise in einem Wörterbuch zu finden sein oder es handelt sich um einen Namen. Wenn dieser Name Rückschlüsse auf Sie zulässt, könnte es einfach zu erraten sein. Falls das Passwort in einem Wörterbuch vorhanden ist, wird es sehr schnell geknackt sein."
    },
    "onlyNumbers": {
        "name": "Zeichendiversität: Nur Nummern",
        "message": "Das Passwort beinhaltet nur Nummern. Das reduziert die möglichen Kombinationen drastisch. Das Passwort wird sehr schnell geknackt."
    },
    "wordAndNumber": {
        "name": "Möglicherweise ein Wort und eine Nummer",
        "message": "Das Passwort sieht so aus, als wäre es nur ein Wort und eine Nummer. Das ist ein sehr häufiges Muster und wird sehr rasch geknackt sein."
    },
    "lengthShort": {
        "name": "Länge: Kurz",
        "message": "Das Passwort ist recht kurz. Je länger ein Passwort ist, desto sicherer wird es sein."
    },
    "justLetters": {
        "name": "Zeichendiversität: Nur Buchstaben",
        "message": "Das Passwort besteht nur aus Buchstaben. In dem Zahlen und Symbole (#, @, -, * etc.) hinzugefügt werden, wird das Passwort sicherer."
    },
    "noSymbols": {
        "name": "Zeichendiversität: Keine Symbole",
        "message": "Das Passwort enthält nur Nummern und Buchstaben. Durch das Hinzufügen von Symbolen (#, @, -, * etc.) wird das Passwort sicherer. Sogar Leerzeichen in einem Passwort sind in vielen Fällen erlaubt. "
    },
    "telephone": {
        "name": "Möglicherweise eine Telefonnummer oder ein Datum",
        "message": "Das Passwort ähnelt einer Telefonnummer oder einem Datum. Wenn das Datum Rückschlüsse auf Sie zulässt, könnte es einfach zu erraten sein. "
    },
    "repeatedPattern": {
        "name": "Muster wiederholt sich",
        "message": "Sich wiederholende Zeichen machen das knacken des Passworts sehr einfach."
    },
    "nonStandardCharacters": {
        "name": "Zeichendiversität: Unübliche Zeichen",
        "message": "Das Passwort enthält unübliche Zeichen. Es sollte deshalb etwas sicherer sein, als gewöhnlich."
    },
    "lengthLong": {
        "name": "Länge: lang",
        "message": "Das Passwort ist über 16 Zeichen lang. Es sollte deshalb etwas sicherer sein, als kurze Passwörter."
    }
}

/*Zahlendefinitionen */
/* hsimp.setNamedNumberDictionary(); */
{
   "hundert": 2,
   "tausend": 3,
   "Millionen": 6,
   "Billionen": 9,
   "Trillionen": 12,
   "Quadrillionen": 15,
   "Quintillionen": 18,
   "Sextillionen": 21,
   "Septillionen": 24,
   "Octillionen": 27,
   "Nonillionen": 30,
   "Decillionen": 33,
   "Undecillionen": 36,
   "Duodecillionen": 39,
   "Tredecillionen": 42,
   "Quattuordecillionen": 45,
   "Quindecillionen": 48,
   "Sexdecillionen": 51,
   "Septendecillionen": 54,
   "Octodecillionen": 57,
   "Novemdecillionen": 60,
   "Vigintillionen": 63,
   "Unvigintillionen": 66,
   "Duovigintillionen": 69,
   "Tresvigintillionen": 72,
   "Quattuorvigintillionen": 75,
   "Quinquavigintillionen": 78,
   "Sesvigintillionen": 81,
   "Septemvigintillionen": 84,
   "Octovigintillionen": 87,
   "Novemvigintillionen": 90,
   "Trigintillionen": 93,
   "Untrigintillionen": 96,
   "Duotrigintillionen": 99,
   "Googol": 100,
   "Trestrigintillionen": 102,
   "Quattuortrigintillionen": 105,
   "Quinquatrigintillionen": 108,
   "Sestrigintillionen": 111,
   "Septentrigintillionen": 114,
   "Octotrigintillionen": 117,
   "Noventrigintillionen": 120,
   "Quadragintillionen": 123,
   "Quinquagintillionen": 153,
   "Sexagintillionen": 183,
   "Septuagintillionen": 213,
   "Octogintillionen": 243,
   "Nonagintillionen": 273,
   "Centillionen": 303,
   "Uncentillionen": 306,
   "Duocentillionen": 309,
   "Trescentillionen": 312,
   "Decicentillionen": 333,
   "Undecicentillionen": 336,
   "Viginticentillionen": 363,
   "Unviginticentillionen": 366,
   "Trigintacentillionen": 393,
   "Quadragintacentillionen": 423,
   "Quinquagintacentillionen": 453,
   "Sexagintacentillionen": 483,
   "Septuagintacentillionen": 513,
   "Octogintacentillionen": 543,
   "Nonagintacentillionen": 573,
   "Ducentillionen": 603,
   "Trecentillionen": 903,
   "Quadringentillionen": 1203,
   "Quingentillionen": 1503,
   "Sescentillionen": 1803,
   "Septingentillionen": 2103,
   "Octingentillionen": 2403,
   "Nongentillionen": 2703,
   "Millinillionen": 3003
}

/* Zeitdefinitionen */
/* hsimp.setPeriodDictionary(); */
[
    {
        "singular": "Yoctosekunde",
        "plural": "Yoctosekunden",
        "seconds": 1e-24
    },
    {
        "singular": "Zeptosekunde",
        "plural": "Zeptosekunden",
        "seconds": 1e-21
    },
    {
        "singular": "Yttosekunde",
        "plural": "Yttosekunden",
        "seconds": 1e-18
    },
    {
        "singular": "Femtosekunde",
        "plural": "Femtosekunden",
        "seconds": 1e-15
    },
    {
        "singular": "Picosekunde",
        "plural": "Picosekunden",
        "seconds": 1e-12
    },
    {
        "singular": "Nanosekunde",
        "plural": "Nanosekunden",
        "seconds": 1e-9
    },
    {
        "singular": "Mikrosekunde",
        "plural": "Mikrosekunden",
        "seconds": 1e-6
    },
    {
        "singular": "Millisekunde",
        "plural": "Millisekunden",
        "abbreviations": ["ms", "msec"],
        "seconds": 1e-3
    },
    {
        "singular": "second",
        "plural": "Sekunden",
        "abbreviations": ["s", "sec", "secs"],
        "seconds": 1
    },
{
        "singular": "Minute",
        "plural": "Minuten",
        "abbreviations": ["m", "min", "mins"],
        "seconds": 60
    },
    {
        "singular": "Stunde",
        "plural": "Stunden",
        "abbreviations": ["h"],
        "seconds": 3600
    },
    {
        "singular": "Tag",
        "plural": "Tage",
        "seconds": 86400
    },
    {
        "singular": "Woche",
        "plural": "Wochen",
        "seconds": 604800
    },
    {
        "singular": "Monat",
        "plural": "Monate",
        "seconds": 2626560
    },
    {
        "singular": "Jahr",
        "plural": "Jahre",
        "seconds": 31557600
    }
]
</details>

**Comment by smallhadroncollider** [comment]
Thanks very much. I'll try and get that added to the PureScript repo and to the website itself in the next month or so (sorry, probably won't be sooner than that - baby to look after and work stuff to do!)

**Comment by smallhadroncollider** [comment]
I'll close this issue and put the German translation as an issue on the PureScript one.
