### ISSUE TITLE
Repeated pattern punished too hard

### ISSUE THREAD

**Issue by TJbiz** [howsecureismypassword/hsimp#11]
A 'good' (green) password turns into an 'OK' (orange) password when adding a 'repeated pattern' (3 identical characters) to the password (it doesn't matter where, i.e. the beginning/middle/end). This doesn't seem right to me: the password still gets stronger (because longer), and definitely not weaker. A better approach might be to not take into account the repeated characters when looking at the length of the password (though some sources say it's still better to pad a password with a certain character than to use a shorter password).

**Comment by TJbiz** [comment]
ps: Not related at all, but I don't know how to pass a comment otherwise -- unless via Twitter, but I don't have an account: the HSIMP score dropped to a 'B' on the Qualys SSL Server Test: https://www.ssllabs.com/ssltest/analyze.html?d=howsecureismypassword.net

pps: I hope my comments aren't discouraging -- I still think your password checker is the best one around! :-)

**Comment by smallhadroncollider** [comment]
Thanks for the heads up on SSL Labs. Haven't checked it for a while.

Regarding the colour going to orange: you'll notice that the calculation time still goes up (longer is *always* better). Basically if you have any notifications marked as a "warning" it's impossible to go into green. I think some crackers do check for repeated patterns first as they're more likely, as such I do think that it should be a "warning" as opposed to a "notice".

**Comment by smallhadroncollider** [comment]
Back to A+ again: https://www.ssllabs.com/ssltest/analyze.html?d=howsecureismypassword.net
