### ISSUE TITLE
Build howsecureismypassword.net as a single HTML page

### ISSUE THREAD

**Issue by dolmen** [howsecureismypassword/hsimp#15]
Change the build of http://howsecureismypassword.net to embed the CSS and JS resource inside the HTML page so I can easily get the page with curl and run it locally.

**Comment by smallhadroncollider** [comment]
There are various performance reasons to not embed all the code on the page itself. This plugin is functionality equivalent, it just looks different. So your best bet would be to get this code running on your machine.

**Comment by dolmen** [comment]
My point was to be able to load the page with a `file://` URL as that forbids external calls so is a simple way to run the code in a browser in a controlled environment.

**Comment by smallhadroncollider** [comment]
As I said, you can use the plugins to do this. The plugins are open source, howsecureismypassword.net is not.
