### ISSUE TITLE
Too much code

### ISSUE THREAD

**Issue by dolmen** [howsecureismypassword/hsimp#16]
When beautifying the JS code of https://howsecureismypassword.net/ I get more than 11600 lines of JS code. Are we supposed to trust that?

**Comment by smallhadroncollider** [comment]
Most of the code is React and various libraries that the site uses. The actual calculation code is all done using the various modules from this github organisation, which don't make up much code at all (although it's all very old and a bit horrible by modern standards).

Not sure what that has to do with trust: you could write something in a couple of lines of code that did something malicious. If you're worried about such things you can use the Network monitor to check the site isn't sending data anywhere.
