### ISSUE TITLE
Character counter

### ISSUE THREAD

**Issue by Peneheals** [howsecureismypassword/hsimp#18]
It would be great to see a character counter somewhere (on the webpage and the bower-installed build also: next to the password field (or below)), to improve the message that a few more characters mean a great impact on password strength.

And it would be great to link the well-known https://xkcd.com/936/ through that "number" (a gamified/funny explanation is always a good choice to spread the message).

**Comment by smallhadroncollider** [comment]
Thanks for the suggestions.

From seeing people use the site, they mostly just type stuff in and notice fairly quickly that the more they type the bigger the number gets. I'm not convinced having an exact length really adds anything.

As for the xkcd comic: although the key idea is right, I feel like it might encourage some bad practices.

The site *does* need a bit more information about what makes a good password. I hope to add this at some point, but this project is lower priority for me at the moment.
