### ISSUE TITLE
"Most used passwords" not case-sensitive

### ISSUE THREAD

**Issue by weis0061** [howsecureismypassword/hsimp#2]
These passwords:
Password
password
PAssword
PaSSword
PASSWORD
PasSWOrd

all appear as "top 5 passwords", yet there are 6 right here. Something's not right.

**Comment by smallhadroncollider** [comment]
The code converts everything to lower-case before checking against the top 10,000 password dictionary. It can lead to some slightly confusing results (such as the one above), but I think it's right to highlight any combination of the top 10,000 words, as a cracking tool will try all combinations of those words (plus many many more - but using a full password dictionary would make the site very slow).
