### ISSUE TITLE
Why is space more secure than hyphen?

### ISSUE THREAD

**Issue by LeoLapworthKT** [howsecureismypassword/hsimp#22]
https://howsecureismypassword.net/

'this is a test' = 111 thousand years
'this-is-a-test' = 30 thousand years

Or

'table book tree' = 5 million years
'table-book-tree' = 1 million years

Isn't there the same.. or even more entropy with a `-` ?

**Comment by smallhadroncollider** [comment]
I think I made that call based on the fact most people don't use spaces in passwords. I think a quick look at the cracking tools suggested a `-` was more likely to be checked than a space.

**Comment by LeoLapworthKT** [comment]
Interesting.. wonder why, I guess spaces then cause issues with quoting if used on a commandline or something.

Appreciate the feedback

**Comment by smallhadroncollider** [comment]
Certainly historically lots of sites/apps wouldn't let you use a space in the password. I've never really been sure why.

**Comment by smallhadroncollider** [comment]
I guess it's hard to list in a list of symbols: `_-? *&` <- hard to spot the space
