### ISSUE TITLE
correcthorsebatterystaple derivatives

### ISSUE THREAD

**Issue by longrunningprocess** [howsecureismypassword/hsimp#4]
Would you consider adding some derivatives to the common passwords?  I know lots of people enjoy this comic and I would hate to learn someone is using some derivative of that password :-)

horsebatterystaple
staplebatterycorrecthorse
...

**Comment by smallhadroncollider** [comment]
I guess the question would be which derivatives to include. Would be useful to know which ones are included in common password dictionaries.

**Comment by longrunningprocess** [comment]
agreed, it's a bit of a guessing game for sure.  I don't know what the right answer is to that.

**Comment by smallhadroncollider** [comment]
Looking through [CrackStation's Password Cracking Dictionary](https://crackstation.net/buy-crackstation-wordlist-password-cracking-dictionary.htm), there are plenty of passwords that include "horse", "battery", "staple", and "correct". So couldn't just use a simple substring check for it to always make sense as an XKCD reference.

**Comment by HisDewness** [comment]
So does this mean it can be implemented? Or are you saying that it isn't practical?

**Comment by smallhadroncollider** [comment]
I think it would be hard to get it "right" - as I'm not sure what that would mean in this case.

**Comment by longrunningprocess** [comment]
yeah, I agree will @smallhadroncollider , not sure how to get this "right", ok if I just close this then?

**Comment by smallhadroncollider** [comment]
Hopefully when I get better dictionary checks implemented it won't need special consideration.
