### ISSUE TITLE
why the result is different?

### ISSUE THREAD

**Issue by januridp** [howsecureismypassword/hsimp#5]
saya tulis sandi di web howsecureismypassword.net dan saya bandingkan dengan source code yg saya unduh. why the result is different?

**Comment by smallhadroncollider** [comment]
I don't speak Indonesian(?), but here goes with Google Translate:

Situs web menggunakan nilai yang berbeda untuk `calculationsPerSecond`. Kode ini sama, konfigurasi hanya berbeda.

(The web site uses a different value for `calculationsPerSecond`. The code is the same, just different configuration.)
