### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by Tinsus** [howsecureismypassword/hsimp#8]
Hi there first of all: thanks for the great JS! I just love it.

But it is possible to build an option to overwrite the existing messages?

I think about the texts for common or possiblyWord and also "name of the numbers". I want to make some messages shorter for my site. And for the numbers: I want to show the number in digits (is more fun to see the zeros rising).

**Comment by smallhadroncollider** [comment]
Thanks, glad you're enjoying it.

The [underlying code does support using different languages/dictionaries](https://github.com/howsecureismypassword/modules-main/blob/develop/main.js#L81-L86), however I'm not exposing them in this package. I'll look at adding support for them.

**Comment by smallhadroncollider** [comment]
I've added the language methods now. Basic documentation in the readme.

There's an example of basic usage here: https://github.com/howsecureismypassword/hsimp/blob/master/build/index.html#L104-L108
